String returnUrl(String platform, String id) {
  const Map<String, String> platforms = {
    'url': '',
    'email': 'mailto:',
    // 'company': 'https://business_rounded.com/',
    // 'at': 'https://alternate_email_rounded.com/',
    // 'location': 'https://location_on_rounded.com/',
    'github': 'https://github.com/',
    'twitter': 'https://twitter.com/',
    // 'youtube': 'https://youtube.com/',
    'instagram': 'https://instagram.com/',
    // 'facebook': 'https://facebook.com/',
    'tiktok': 'https://tiktok.com/@',
    'linkedin': 'https://www.linkedin.com/in/',
    // 'discord': 'https://discord.com/',
    // 'slack': 'https://slack.com/',
    // 'figma': 'https://figma.com/',
    // 'stackOverflow': 'https://stackOverflow.com/',
    // 'dribbble': 'https://dribbble.com/',
    // 'medium': 'https://medium.com/',
    // 'codepen': 'https://codepen.com/',
    // 'dropbox': 'https://dropbox.com/',
    // 'cloudflare': 'https://cloudflare.com/',
    // 'airbnb': 'https://airbnb.com/',
    // 'vimeo': 'https://vimeo.com/',
    // 'whatsapp': 'https://whatsapp.com/',
    // 'line': 'https://line.com/',
    // 'telegram': 'https://telegram.com/',
    // 'pinterest': 'https://pinterest.com/',
    // 'googleplay': 'https://googlePlay.com/',
    // 'gitlab': 'https://gitlab.com/',
    // 'twitch': 'https://twitch.com/',
    // 'xbox': 'https://xbox.com/',
    // 'unity': 'https://unity.com/',
    // 'trello': 'https://trello.com/',
    // 'tumblr': 'https://tumblr.com/',
    // 'swift': 'https://swift.com/',
    // 'reddit': 'https://reddit.com/',
    // 'sketch': 'https://sketch.com/',
    // 'mastodon': 'https://mastodon.com/',
    // 'spotify': 'https://spotify.com/',
  };

  final url = '${platforms[platform]}$id';
  return url;
}
