include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint

linter:
  rules:
    - always_use_package_imports
    - avoid_void_async
    - directives_ordering
    - flutter_style_todos
    - prefer_single_quotes
    - require_trailing_commas
    - unawaited_futures
    - unnecessary_statements
    - unsafe_html
