name: Deploy to Preview Channel

on:
  pull_request:

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      - name: Doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter packages get

      - name: Build web
        run: flutter build web

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_THUNDERCARD_TEST }}"
          expires: 14d
          projectId: thundercard-test