name: Format Suggestion

on:
  pull_request

concurrency:
  group: format-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:

      - name: Install dependencies
        run: flutter pub get
      - name: Analyze
        run: flutter analyze --no-pub
      - uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: flutter analyze
