name: Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2.10.0
        with:
          channel: stable

      - name: Doctor
        run: flutter doctor

      - name: Install dependencies
        run: flutter packages get

      - name: Format
        run: dart format lib test --set-exit-if-changed

      - name: Analyze
        run: flutter analyze lib test

      - name: Run tests
        run: flutter test --coverage --coverage-path=lcov.info

      - uses: codecov/codecov-action@v3.1.4
